#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2022 Estudios 6/8 (bakumapu@gmail.com)
# 
# This program is part of Bakumapu and is released under
# the GPLv2 License: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

import sys
import subprocess

BAKU_URL = "https://github.com/polirritmico/bakupipe.git"
BAKUPIPE_URL = "https://github.com/polirritmico/bakumapu.git"

def check_is_baku_repo():
    _command = "git config --get remote.origin.url"
    _proc = subprocess.Popen(_command.split(),
                             stdout=subprocess.PIPE,
                             universal_newlines=True)
    output = str(_proc.communicate()[0])

    if output == BAKU_URL or output == BAKUPIPE_URL:
        return False
    return True


def mk_pre_deploy_branch():
    _command = "git branch -b pre-deploy"
    _proc = subprocess.Popen(_command.split(), stdout=subprocess.PIPE)
    return _proc.communicate()

def main(argv):
    if argv[0] != "deploy":
        print("ERROR")
        return 1

    print("Init deploy pipeline...")

    if not check_is_baku_repo():
        return 1

    print("Creando rama pre-deploy")

    mk_pre_deploy_branch()

    print("Merge a pre-deploy")

    print("")

    print("")

    print("")

    print("")

    print("")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
