# ======  BAKUPIPE CONFIG FILE  ======#
# Put this file inside pipeline/
# Don't change lists to strings or vice versa.
---
## Git repository
# Project repositories URLs
PROJECT_URLS:
  - https://github.com/polirritmico/bakumapu.git
  - https://github.com/polirritmico/bakupipe.git

# WORK BRANCH
WORK_BRANCH: pre-deploy

# Default branches
DEFAULT_BRANCH: develop
DEFAULT_DEPLOY_BRANCH: deploy
DEFAULT_RELEASE_BRANCH: release
DEFAULT_BRANCHES_LIST:
  - develop
  - deploy
  - release

# Artifacts repositories commands
DRIVE_PUSH_COMMAND: drive push -quiet -files
